### ISSUE TITLE
example in docker compose please?

### ISSUE THREAD

**Issue by jlobos** [pierreprinetti/certbot#4]

**Comment by jackmac92** [comment]
@jlobos was looking for the same thing, my solution was to create a boot script that runs the provided command first, then calls docker-compose up. 
```
docker volume create --name nginx-certs

docker run \
  -v nginx-certs:/etc/letsencrypt \
  -e http_proxy=$http_proxy \
  -e domains="DOMAINS" \
  -e email="EMAIL" \
  -p 80:80 \
  -p 443:443 \
  --rm pierreprinetti/certbot:latest

docker-compose up --build
```

added the following to my pre-existing nginx container in docker-compose.yml

```
services:
    nginx:
        volumes:
            - nginx-certs:/etc/nginx/certs:ro
```

and added this to the end of docker-compose.yml
```
volumes:
    nginx-certs:
```

not ideal but works for now

**Comment by jlobos** [comment]
yes works!, thanks @jackmac92

**Comment by pierreprinetti** [comment]
```
version: '3'
services:
  nginx:
    [...]
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
[...]
volumes:
  nginx-certs:
    external:true
```

This is what I've done as well :)

**Comment by KristerV** [comment]
so there's no way to start it with docker-compose or what? 

```
  certbot:
    image: pierreprinetti/certbot:latest
    volumes:
      - nginx-certs:/etc/letsencrypt
    environment:
      - domains=example.com
      - email=me@gmail.com
```

This is as far as I'm getting, but it doesn't work. Only getting authrozation errors from Let's Encrypt when it tries to connect.
